### ISSUE TITLE
protoc for c version

### ISSUE THREAD

**Issue by aholtzma-6h** [acg/lwpb#10]
Where can I find the version of protoc that will generate C files like the ones included in the repository?

**Comment by acg** [comment]
Possibly via the [proto-c](https://github.com/protobuf-c/protobuf-c) project? I'm not exactly sure how Simon generated those C files.

**Comment by aholtzma-6h** [comment]
No, the output is very different. The generated files look LWPB specific, so it may have been a custom version of protoc-c. I guess I will just manually generate the message descriptors myself.

**Comment by acg** [comment]
Okay. Those generated C files were added early on for testing lwpb against a reference implementation. I haven't touched them since I inherited the project. If you're trying to extend the lwpb test suite, it might be worth hunting down the generator. But if you're just looking for a protobuf C code generator, I'd suggest protoc-c.
